### ISSUE TITLE
Error while login

### ISSUE THREAD

**Issue by Ba1in** [sumithemmadi/truecallerpy#15]
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\balin\AppData\Roaming\Python\Python310\Scripts\truecallerpy.exe\__main__.py", line 7, in <module>
  File "C:\Users\balin\AppData\Roaming\Python\Python310\site-packages\truecallerpy\app.py", line 294, in ExecuteTrurcallerPy
    truecallerpy_login_with_file(config)
  File "C:\Users\balin\AppData\Roaming\Python\Python310\site-packages\truecallerpy\truecallerLogin.py", line 248, in truecallerpy_login_with_file
    "installationId": "{}".format(jsonFileData["account"]["installations"][0]["installation"]["id"]),

**Comment by sumithemmadi** [comment]
Truecaller has removed the installationId from the JSON file and now requires users to log in using OTP (One-Time Password).

**Comment by FedericoDM** [comment]
H! @sumithemmadi, can we get the InstallationId after entering the OTP?

**Comment by sumithemmadi** [comment]
Yes, you can get the installation id. To obtain the installation ID, you can enter the command `truecallerpy -i` into the terminal.

**Comment by nanda16ameer** [comment]
hii @sumithemmadi , Is there any way to bypass {'errorCode': 429, 'errorMessage': 'too many requests.', 'data': None} ?

**Comment by sumithemmadi** [comment]
@nanda16ameer  No , but you can use multiple installationIds to search
